# This YAML configuration defines various messages (and associated error codes per module).
# Module can be a single controller OR multiple controller grouped in logical manner.

global: # define all global error messages and codes here
  internalError:
    message: Internal Error
    errorCode: 99
  success:
    message: Successfully completed.
  tooManyRequests:
    message: Too many wrong passwords, please try after 10 minutes.
    errorCode: 102
    httpErrorCode: 429
  uniqueValidation:
    message: already exists.
    errorCode: 100
    httpErrorCode: 400
  sequelizeValidation:
    message: Validation error(s)
    errorCode: 101
    httpErrorCode: 400
user: # module name
  moduleId: 2000 # module ID. Make sure it is unique across all projects.
  usernameAlreadyExists: # error message key
    message: Username is already in use. # error message
    errorCode: 10001 # module ID + error sequence number
    httpErrorCode: 400
  emailIdAlreadyExists: # error message key
    message: Email Id is already in use. # error message
    errorCode: 10002 # module ID + error sequence number
    httpErrorCode: 400
category:
  categoriesNotFound:
    message: Category details not found.
    errorCode: 30001
    httpErrorCode: 400
  subcategories:
    message: Subcategory details not found.
    errorCode: 30002
    httpErrorCode: 400
club:
  clubAlreadyExists: # error message key
    message: Club name and location is already in use. # error message
    errorCode: 10002 # module ID + error sequence number
    httpErrorCode: 400
tournament:
  tournamentAlreadyExists:
    message: Tournament not already exisiting.
    errorCode: 50001
    httpErrorCode: 400
security: # module name
  moduleId: 2000 # module ID. Make sure it is unique across all projects.
  invalidUserNamePasswd: # error message key
    message: Invalid username or password. # error message
    errorCode: 20001 # module ID + error sequence number
    httpErrorCode: 400
  invalidTokenUser: # error message key
    message: Invalid token. # error message
    errorCode: 20002 # module ID + error sequence number
    httpErrorCode: 400
  referralSourceLocked:
    message: Organization locked. Please contact administrator. # error message
    errorCode: 20003 # module ID + error sequence number
    httpErrorCode: 400
  referralSourceInactive:
    message: Your account has been deactivated due to a long period of inactivity. Please email Gento at staffing@gento.io to activate your account. # error message
    errorCode: 20005 # module ID + error sequence number
    httpErrorCode: 400
  invalidSecret: # error message key
    message: Invalid secret value. All headless user login request must be provided with secret value. # error message
    errorCode: 20004 # module ID + error sequence number
    httpErrorCode: 400

securityToken: # module name
  moduleId: 6001 # module ID. Make sure it is unique across all projects.
  tokenAuthenticationFailed: # error message key
    message: Failed to authenticate the token. Access denied. Please login again!! # error message
    ## errorCode: No need since HTTP 403 will be enough.
  noTokenProvided: # error message key
    message: No token provided. Access denied! # error message
    ## errorCode: No need since HTTP 403 will be enough.
